# Generated by Django 2.1.7 on 2020-03-16 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('-created',)},
        ),
    ]
