# Generated by Django 2.1.7 on 2020-05-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_video_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='thumbnail'),
            preserve_default=False,
        ),
    ]
